export const EVALUATE_EXPRESSION = "EVALUATE_EXPRESSION"
export const RECEIVE_RESULT = "RECEIVE_RESULT"
export const UPDATE_HISTORY = "UPDATE_HISTORY"
export const CHANGE_EXPRESSION_TYPE = "CHANGE_EXPRESSION_TYPE"
